version: "3.8"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    depends_on:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=rasitesdmr
      - SONARQUBE_JDBC_PASSWORD=rasitesdmr
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql-database:5432/sonarqube_db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9009:9000"

  sonarqube-database:
    container_name: sonarqube-database
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: rasitesdmr
      POSTGRES_PASSWORD: rasitesdmr
      POSTGRES_DB: sonarqube_db

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_database_data: