package com.rasitesdmr.orchestratorservice.enums;

public enum SagaStepEventType {
    TOPIC_BOOKING_CREATED,
    TOPIC_PAYMENT_START,
    TOPIC_PAYMENT_COMPLETED,
    TOPIC_PAYMENT_BOOKING_COMPLETED,
    TOPIC_FLIGHT_START,
    TOPIC_FLIGHT_CONFIRMED,
    TOPIC_FLIGHT_BOOKING_CONFIRMED,
    TOPIC_HOTEL_START,
    TOPIC_HOTEL_BOOKED,
    TOPIC_HOTEL_BOOKING_BOOKED,
    TOPIC_BOOKING_CONFIRMED,
    TOPIC_PAYMENT_FAILED,
    TOPIC_PAYMENT_BOOKING_FAILED,
    TOPIC_FLIGHT_FAILED,
    TOPIC_FLIGHT_PAYMENT_REVERSE_START,
    TOPIC_FLIGHT_PAYMENT_REVERSED,
    TOPIC_FLIGHT_BOOKING_FAILED,
    TOPIC_HOTEL_FAILED,
    TOPIC_HOTEL_FLIGHT_REVERSE_START,
    TOPIC_HOTEL_FLIGHT_REVERSED,
    TOPIC_HOTEL_PAYMENT_REVERSE_START,
    TOPIC_HOTEL_PAYMENT_REVERSED,
    TOPIC_HOTEL_BOOKING_FAILED
}
