version: '3.8'
services:

  db-container:
    container_name: postgresql
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: rasitesdmr
      POSTGRES_PASSWORD: rasitesdmr
      POSTGRES_DB: unit-test
    networks:
      - network

networks:
  network:
    driver: bridge
    name: postgresql